version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: piclo
      POSTGRES_PASSWORD: piclo
      POSTGRES_DB: piclo
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: